#!/bin/bash

Preparing NAMD protein mutation files for running FEP calculation using CHARMM and [alchemify](https://github.com/jhenin/alchemify).

# Step 1. 
# extract protein segment where the point mutation will be defined
# and extract everything else seperately
charmm -i extract_segs.inp

# Step 2.
# mutate the residue
charmm -i mutate.inp

# Step 3.
# merge all the segments and then we can go to NAMD
charmm -i complex.inp

# Step 4. 
# add exclusion lists
alchemify solvent.psf solvent.fep.psf solvent.pdb


exit 0

Issues: /Home/siv32/pga043/Software/vmd-1.9.4a57/lib/vmd/plugins/noarch/tcl/readcharmmtop1.2/top_all36_hybrid.inp
top_all36_hybrid.inp =>

    ATOM HA   HB => this is wrong, it should be HB1 since there is no atom-type HB (as far as I understand).

maybe there are more of such mistakes and maybe that's why the mutator plugin in VMD fails for W2F mutation.
    confirmed, I just changed the atom type and it worked!!

Enjoy!


See FEP tutorials here:
http://pmx.mpibpc.mpg.de/tripep.pl
https://degrootlab.github.io/pmx/tutorials/aminoacid_tutorial.html
https://www.ks.uiuc.edu/Training/Tutorials/namd/FEP/tutorial-FEP.pdf

